version: "3.8"
services:
  python-backend:
    build:
      context: ../agents-python
      dockerfile: ../infra/Dockerfile.python
    ports:
      - "8000:8000"

  java-backend:
    build:
      context: ../backend-java/WorkflowService
      dockerfile: ../../infra/Dockerfile.java
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../agenthive-frontend
    ports:
      - "5173:5173"

